[master]
  runner = "s3://ambiata-dist/master-ambiata/master-haskell-library-0.0.1-20151013064111-d6a3241"
  version = 1
  sha1 = "53221a5acfd276d578b1ebb232516d5f42ba4cca"

[build.dist]
  HADDOCK = "true"

[build.branches]
